---
title: "metaDataAllScopeStop"
author: "Melanie Smith"
date: "13 September 2023"
output: html_document
---

# Load required libraries
```{r load Libraries}
library(plyr)
library(reshape2)
library(dplyr)
library(stringr)
library(edgeR)
library(readxl)
library(readr)
library(magrittr)
library(tibble)
library(ggplot2)
library(ggrepel)
library(pheatmap)

# set project directory
projectDir <- "/home/smit1924/preeclampsia_sex_chromosome_informed"
dataFolder <- "/home/smit1924/dataFolder"

expt_name <- 'metaData_SCOPE_STOP'

SCOPE_dataDictionary_file <- file.path("/media/sf_D_DRIVE/VM_Projects/dataFolder/Data_dictionary_FINAL_DISTR_updated_130215_biomarker_SNP.xlsx")
SCOPE_raw_file <- file.path("/media/sf_D_DRIVE/VM_Projects/dataFolder/SCOPE_full_raw_20141201.rds")
STOP_raw_dat_file <- file.path(dataFolder,"STOPStudy_DATA_2021-04-23_1151.csv")
STOP_raw_dict_file <- file.path(dataFolder,"STOPStudy_DataDictionary_2021-04-23.csv")
metadata_file <- file.path(projectDir, "clearBoxRawData/cleanSampleMetadata.csv")

outdir <- file.path(projectDir, paste0(expt_name, "_output"))

dir.create(outdir)

# REDCap import
source("/media/sf_D_DRIVE/VM_Projects/dataFolder/redcap_api_import.R")

```

# Import sample names and metadata table
- we will use this to subset the filtered data
```{r}
# vector of only the samplenames we're intersted in
sample_names <- readRDS("~/preeclampsia_sex_chromosome_informed/clearBoxCleanData/sample_names.rds")
metadata <- read_csv(file = metadata_file)
```

# Import SCOPE
```{r}

# import the full SCOPE metadata file
SCOPE_raw <- readRDS(SCOPE_raw_file)

# import SCOPE full data dictionary
SCOPE_dataDictionary <- read_excel(SCOPE_dataDictionary_file,
                                   sheet = "Stage 1 Data") %>%
  as.data.frame()

# lets find all of the possible BP variables
matches <- grepl("sbp|dbp", SCOPE_dataDictionary$Variable_SAS_name, ignore.case = TRUE)
filtered_data <- SCOPE_dataDictionary[matches, ]


# SCOPE BP variables of interest 
SCOPE_variables <- c("f11c_1st_vst_map_1st", "f11c_1st_vst_map_2nd", "f24_Max_sBP", "f24_Max_dBP")
all_STOP_bloodPressure <- c("f11_1st_sbp", "f11_1st_dbp",
                            "f11_2nd_sbp", "f11_2nd_dbp",
                            "f11_3rd_sbp_microlife", "f11_3rd_dbp_microlife",
                            "f11_4th_sbp_microlife", "f11_4th_dbp_microlife",
                            "f11c_1st_vst_mean_sbp", "f11c_1st_vst_mean_dbp",
                            "f20_1st_sbp", "f20_1st_dbp",
                            "f20_2nd_sbp", "f11_2nd_dbp",
                            "f20_3rd_sbp_microlife", "f20_3rd_dbp_microlife",
                            "f20_4th_sbp_microlife", "f20_4th_dbp_microlife",
                            "f20c_2nd_vst_mean_sbp", "f20c_2nd_vst_mean_dbp",
                            "f24_sBP", "f24_dBP",
                            "f24_Max_sBP", "f24_Max_dBP",
                            "f35_Max_sBP_Adm", "f35_Max_dBP_Adm",
                            "f35_Max_sBP_ap", "f35_Max_dBP_Adm",
                            "f35_Max_sBP_pp", "f35_Max_dBP_pp",
                            "f35_sBP_Adm", "f35_dBP_Adm",
                            "f35_sBP_ap", "f35_dBP_ap",
                            "f35_sBP_pp", "f35_dBP_pp",
                            "f35c_f24_highest_sbp", "f35c_f24_highest_dbp",
                            "f11c_Gest")
# filter
filter_SCOPE_dataDictionary <- subset(SCOPE_dataDictionary, Variable_SAS_name %in% all_STOP_bloodPressure)


# subset to the required columns
subsetSCOPE <- dplyr::select(SCOPE_raw, regid, centre, all_of(all_STOP_bloodPressure)) %>% 
  # remove all centres except Adelaide
  dplyr::filter(., centre == "Adelaide University") %>% 
    # sort by ID
  dplyr::arrange(., regid) %>% 
  # add a samplename column that matches the rest of my data
  dplyr::mutate(., samplename = paste0("SCP", stringr::str_pad(regid, width=4, pad="0"))) %>%
  # make samplename the first column and drop column 'centre'
  dplyr::select(., samplename, everything(), -centre) %>% 
  # replace all the missing data codes with NA
  mutate(across(everything(), function(x){replace(x, which(x<0), NA)}))
head(subsetSCOPE)
dim(subsetSCOPE)

# subset to include on the samples in the PE study
subsetSCOPE %<>% subset(., samplename %in% sample_names)

# lets check to see how many NAs the data has
na_summary_scope <- tibble(
  column = names(subsetSCOPE),
  num_NAs = colSums(is.na(subsetSCOPE))
)
print(na_summary_scope)

# Remove the "f35" variables because they are 21/38 missing data
# make a vector of columns with missing data and NAs
bp_variables_to_drop_scope <- c("f35_Max_sBP_Adm", "f35_Max_dBP_Adm",
                                "f35_Max_sBP_ap", "f35_Max_dBP_Adm",
                                "f35_Max_sBP_pp", "f35_Max_dBP_pp",
                                "f35_sBP_Adm", "f35_dBP_Adm",
                                "f35_sBP_ap", "f35_dBP_ap",
                                "f35_sBP_pp", "f35_dBP_pp")

# drop the columns with missing data and NAs
bp_subsetScope <- subsetSCOPE %>%
  dplyr::select(., -bp_variables_to_drop_scope) %>%
  # add the PE information
  dplyr::left_join(., metadata[, c("samplename", "sex_outcome")], by = "samplename") %>%
  dplyr::select(., samplename, f11c_Gest, sex_outcome, everything(), -regid)


# use dplyr::mutate to make new sbp and dbp columns for the rbind
SCOPE_sbp_dbp <- subsetSCOPE %>%
  dplyr::mutate(., max_sbp = f24_Max_sBP,
                max_dbp = f24_Max_dBP) %>%
  dplyr::select(., samplename, max_sbp, max_dbp)
```

# Import STOP

```{r import STOP}

# STOP (REDCap import)
STOP_raw_dat <- read.csv("/media/sf_D_DRIVE/VM_Projects/dataFolder/STOPStudy_DATA_2021-04-23_1151.csv",
                         header = TRUE)
STOP_raw_dict <- read.csv(file.path("/media/sf_D_DRIVE/VM_Projects/dataFolder/STOPStudy_DataDictionary_2021-04-23.csv"
  ),
                          header = TRUE)

STOP_raw <- apply_data_dict(STOP_raw_dat,STOP_raw_dict)
table(STOP_raw$final_data) #use final data subset (N=1300) only

# STOP BP variables of interest 
# STOP_bloodPressure <- c("participant_id", "f9_sbp", "f9_dbp", "f20_max_sbp_dbp", "f20_sbp_max_dbp")
# this is a vector of every variable in the STOP data dictionary containing "bp" related to blood pressure
all_STOP_bloodPressure <- c("participant_id",
                            "f9_sbp", "f9_dbp",
                            "f9_sbp_uscom", "f9_dbp_uscom",
                            "f9_sbp_central", "f9_dbp_central",
                            "f9_sbp_auto", "f9_dbp_auto",
                            "f11_sbp", "f11_dbp",
                            "f11_sbp_uscom", "f11_dbp_uscom",
                            "f14_34wk_sbp", "f14_34wk_dbp",
                            "f14_34wk_sbp_us", "f14_34wk_dbp_us",
                            "f14_34wk_csbp", "f14_34wk_cdbp",
                            "f20_max_sbp_dbp", "f20_sbp_max_dbp",
                            "uscombp_12w_csbp", "uscombp_12w_cdbp",
                            "uscombp_34w_oscsys", "uscombp_34w_oscdia",
                            "uscombp_34w_csbp", "uscombp_34w_cdbp",
                            "f28_max_sbp_adm", "f28_max_dbp_adm",
                            "f28_max_sbp_ante", "f28_max_dbp_ante",
                            "f28_max_sbp_post", "f28_max_dbp_post",
                            "f28_max_sbp_intrapartum", "f28_max_dbp_intrapartum")
# add the date variables
# f9_12wk_vst_gestw refers to Form 9 visit 12 week variables
ga_12wk_visit <- "f9_12wk_vst_gestw"

# Which of these variables are present in the final data
bp_final_STOP_data <- intersect(all_STOP_bloodPressure, colnames(STOP_raw))
# Which of these variables are missing from the final data
bp_missing_final_STOP_data <- setdiff(all_STOP_bloodPressure, colnames(STOP_raw))

# subset for the variables in the final STOP data
subsetSTOP <- dplyr::select(
  STOP_raw, 
  final_data, 
  all_of(bp_final_STOP_data), 
  all_of(ga_12wk_visit)
  ) %>%
  # drop samples not in the final data subset
  dplyr::filter(., final_data == "Yes") %>% 
  # sort by ID
  dplyr::arrange(., participant_id) %>% 
  # add a samplename column that matches the rest of my data
  dplyr::mutate(., samplename = paste0(
    "STP", stringr::str_pad(participant_id, width = 4, pad = "0"))
    ) %>%
  # make samplename the first column
  dplyr::select(., samplename, everything()) %>%
  # remove the redundent columns
  dplyr::select(., -final_data, -participant_id)
# Keep only the samples we have in the PE data
subsetSTOP %<>% subset(., samplename %in% sample_names)

# lets check to see how many NAs the data has
na_summary <- tibble(
  column = names(subsetSTOP),
  num_NAs = colSums(is.na(subsetSTOP))
)
print(na_summary)

# make a vector of columns with missing data and NAs
bp_variables_to_drop <- c("f9_sbp_auto", "f9_dbp_auto",
                          "f11_sbp", "f11_dbp",
                          "f11_sbp_uscom", "f11_dbp_uscom",
                          "f14_34wk_sbp", "f14_34wk_dbp",
                          "f14_34wk_sbp_us", "f14_34wk_dbp_us",
                          "f14_34wk_csbp", "f14_34wk_cdbp",
                          "uscombp_34w_oscsys", "uscombp_34w_oscdia",
                          "uscombp_34w_csbp", "uscombp_34w_cdbp",
                          "f28_max_sbp_adm", "f28_max_dbp_adm",
                          "f28_max_sbp_ante", "f28_max_dbp_ante",
                          "f28_max_sbp_post", "f28_max_dbp_post",
                          "f28_max_sbp_intrapartum", "f28_max_dbp_intrapartum")

# drop the columns with missing data and NAs
bp_subsetStop <- subsetSTOP %>%
  dplyr::select(., -bp_variables_to_drop) %>%
  # add the PE information
  dplyr::left_join(., metadata[, c("samplename", "sex_outcome")], by = "samplename") %>%
  dplyr::select(., samplename, f9_12wk_vst_gestw, sex_outcome, everything())


# Create new columns by splitting at "/"
bp_subsetStop$max_sbp <- sapply(strsplit(as.character(bp_subsetStop$f20_max_sbp_dbp), "/"),
                                function(x) x[1])
bp_subsetStop$max_dbp <- sapply(strsplit(as.character(bp_subsetStop$f20_max_sbp_dbp), "/"),
                                function(x) ifelse(length(x) > 1, x[2], NA))

# Convert to numeric
bp_subsetStop$max_sbp <- as.numeric(bp_subsetStop$max_sbp)
bp_subsetStop$max_dbp <- as.numeric(bp_subsetStop$max_dbp)

# use dplyr::select to keep only the columns needed for the rbind
STOP_max_sbp_dbp <- dplyr::select(bp_subsetStop, samplename, max_sbp, max_dbp)


## for most samples in STOP there is a recorded measurement for highest sbp (f20_max_sbp_dbp) and highest dbp (f20_sbp_max_dbp) in the format sbp/dbp
## These may or may not be from the same BP measurement.
## We chose here to use the data from the highest sbp measurement here.
## One sample, STP0903 has the highest sbp and dbp listed on their own so when I split the column we end up with an NA for the dbp.
## Here I will add the dbp back in
STOP_max_sbp_dbp$max_dbp[STOP_max_sbp_dbp$samplename == "STP0903"] <- 68


```
## Combine the two sbp dbp objects

```{r}

combined_max_sbp_dbp <- rbind(SCOPE_sbp_dbp, STOP_max_sbp_dbp) %>%
  dplyr::left_join(., metadata, by = "samplename")

## mutate the group names (ie from M_Control to M_Unc and from F_Control to F_Unc)
plot_data <- combined_max_sbp_dbp %>%
  dplyr::mutate(new_sex_outcome = dplyr::case_when(
    sex_outcome == "M_PE" ~ "M_PE",
    sex_outcome == "F_PE" ~ "F_PE",
    sex_outcome == "M_Control" ~ "M_Un",
    sex_outcome == "F_Control" ~ "F_Un",
    TRUE ~ NA_character_  # This handles any unexpected values
  )) %>%
  dplyr::mutate(., new_sex_outcome = factor(new_sex_outcome, levels = c("F_Un", "F_PE", "M_Un", "M_PE")))

# save a clean copy of the max bp data
write_csv(dplyr::select(plot_data, samplename, max_sbp, max_dbp), file = file.path(outdir, "SCOPE_STOP_max_sbp_dbp.csv"))

```

## Test for difference in 12wk blood pressure

```{r}
# quick visualisation
ggplot(bp_subsetStop, aes(x = sex_outcome, y = f9_12wk_vst_gestw)) +
  geom_violin(trim = FALSE, fill = "lightblue") +
  geom_boxplot(width = 0.1, outlier.shape = NA) +
  geom_jitter(width = 0.2, alpha = 0.5) +
  labs(title = "Gestational Age at 12 Week Visit by Sex Outcome",
       y = "Gestational Age (weeks)",
       x = "Sex Outcome") +
  theme_minimal()

# test for normality (fails because PE group is only 2 and min is 3 for this test)
bp_subsetStop %>%
  group_split(sex_outcome) %>%
  purrr::map_df(~{
    data.frame(
      sex_outcome = unique(.x$sex_outcome),
      shapiro_p = shapiro.test(.x$f9_12wk_vst_gestw)$p.value
    )
  })

kruskal.test(f9_12wk_vst_gestw ~ sex_outcome, data = bp_subsetStop)


```


## Make some plots
```{r}
# Create the scatter plot
ggplot(plot_data, aes(x = max_sbp, y = max_dbp, color = sex_outcome, shape = cohort)) +
  geom_hline(yintercept = 90, linetype = "dashed", color = "black", size = 0.8) +
  geom_vline(xintercept = 140, linetype = "dashed", color = "black", size = 0.8) +
  geom_point(alpha = 0.7, size = 3) +
  scale_color_manual(values = c("palegreen3", "#004000", "plum3", "#2A0052"), name = "Sex Outcome") +
  scale_shape_manual(values = c(16, 17, 18, 15, 8), name = "Cohort") +
  labs(
    title = "Relationship between Systolic and Diastolic Blood Pressure",
    x = "Systolic Blood Pressure (mmHg)",
    y = "Diastolic Blood Pressure (mmHg)"
  ) +
  theme_minimal() +
  theme(
    legend.position = "right",
    plot.title = element_text(size = 14, face = "bold"),
    axis.title = element_text(size = 12),
    legend.title = element_text(size = 11, face = "bold")
  )


# Create violin plot with boxplot: SBP by sex outcome
ggplot(plot_data, aes(x = sex_outcome, y = max_sbp, fill = sex_outcome)) +
  geom_violin(trim = FALSE, alpha = 0.7) +
  geom_jitter(width = 0.15, size = 1.5, alpha = 0.6, shape = 21, color = "black", fill = "white") +
  labs(
    title = "Distribution of Systolic Blood Pressure by Sex and Outcome",
    x = "Sex",
    y = "Systolic Blood Pressure (mmHg)"
  ) +
    theme_bw() +  # Clean theme
  scale_fill_manual(values = c("palegreen3", "#004000",  "plum3", "#2A0052")) +
  theme(
    legend.position = "none",
    plot.title = element_text(size = 14, face = "bold"),
    axis.title = element_text(size = 12),
    axis.text.x = element_text(size = 11)
  ) +
  stat_summary(fun = mean, geom = "point", shape = 18, size = 3, color = "black")

# Violin plot with jittered points: SBP by sex outcome
ggplot(plot_data, aes(x = sex_outcome, y = max_dbp, fill = sex_outcome)) +
  geom_violin(trim = FALSE, alpha = 0.7) +
  geom_jitter(width = 0.15, size = 1.5, alpha = 0.6, shape = 21, color = "black", fill = "white") +
  labs(
    title = "Distribution of Systolic Blood Pressure by Sex and Outcome",
    x = "Sex",
    y = "Systolic Blood Pressure (mmHg)"
  ) +
  theme_bw() +  # Clean theme
  scale_fill_manual(values = c("palegreen3", "#004000", "plum3", "#2A0052")) +
  theme(
    legend.position = "none",
    plot.title = element_text(size = 14, face = "bold"),
    axis.title = element_text(size = 12),
    axis.text.x = element_text(size = 11)
  ) +
  stat_summary(fun = mean, geom = "point", shape = 18, size = 3, color = "black")

```

# USCOM data

```{r}
uscom_variables <- c("participant_id",
                     "uscombp_12w_data", "uscombp_12w_machine", "uscombp_12w_sd", "uscombp_12w_datetime", "uscombp_12w_oscsys", "uscombp_12w_oscdia", "uscombp_12w_oscpp", "uscombp_12w_oscmean", "uscombp_12w_oscpr", "uscombp_12w_snr", "uscombp_12w_sspr", "uscombp_12w_prv", "uscombp_12w_aix", "uscombp_12w_dpdtmax", "uscombp_12w_dpdtart", "uscombp_12w_harm", "uscombp_12w_sspp", "uscombp_12w_dpp", "uscombp_12w_ssrwttfoot", "uscombp_12w_ssrwttpeak", "uscombp_12w_sep", "uscombp_12w_csbp", "uscombp_12w_cdbp", "uscombp_12w_cpp", "uscombp_12w_guid", "uscombp_12w_swversion", "uscombp_12w_devid"
                     )
# subset for the variables in the final STOP data
uscom_subsetSTOP <- dplyr::select(STOP_raw, final_data, all_of(uscom_variables)) %>%
  # drop samples not in the final data subset
  dplyr::filter(., final_data == "Yes") %>% 
  # sort by ID
  dplyr::arrange(., participant_id) %>% 
  # add a samplename column that matches the rest of my data
  dplyr::mutate(., samplename = paste0(
    "STP", stringr::str_pad(participant_id, width = 4, pad = "0"))
    ) %>%
  # make samplename the first column
  dplyr::select(., samplename, everything()) %>%
  # remove the redundent columns
  dplyr::select(., -final_data, -participant_id)
# Keep only the samples we have in the PE data
subsetSTOP %<>% subset(., samplename %in% sample_names)

# lets check to see how many NAs the data has
na_summary_uscom <- tibble(
  column = names(uscom_subsetSTOP),
  num_NAs = colSums(is.na(uscom_subsetSTOP))
)
print(na_summary_uscom)



```


